name: main

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"

jobs:
  tags:
    name: Latest tags
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      lsp_tag: ${{ steps.tags.outputs.lsp }}
      sublime_lib_tag: ${{ steps.tags.outputs.sublime_lib }}
      pyright_tag: ${{ steps.tags.outputs.pyright }}
    steps:
      - id: tags
        run: |
          echo "lsp=$(gh release view --repo sublimelsp/LSP --json tagName -q .tagName)" >> "$GITHUB_OUTPUT"
          echo "sublime_lib=$(gh release view --repo sublimelsp/sublime_lib --json tagName -q .tagName)" >> "$GITHUB_OUTPUT"
          echo "pyright=$(gh release view --repo sublimelsp/LSP-pyright --json tagName -q .tagName)" >> "$GITHUB_OUTPUT"

  unittesting:
    name: Unittesting (${{ matrix.os }})
    needs: tags
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - uses: actions/checkout@v6

      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime-text-version: 4
          # Needs to have different name than the dependency to be able to run tests
          package-name: lsp-utils-dep
          extra-packages: |
            sublimelsp/LSP@${{ needs.tags.outputs.lsp_tag }}
            sublimelsp/LSP-pyright@${{ needs.tags.outputs.pyright_tag }}

      - name: Overwrite installed dependency with local version
        shell: bash
        run: |
          # $PACKAGE is exposed from the setup step.

          case ${{ runner.os }} in
            Linux)
              ST_LIBS_DIR="$HOME/.config/sublime-text/Lib/python38";;
            macOS)
              ST_LIBS_DIR="$HOME/Library/Application Support/Sublime Text/Lib/python38";;
            Windows)
              ST_LIBS_DIR="/c/st/Data/Lib/python38/";;
            *)
              exit 1
          esac

          cd ./
          # detached head will crash package control
          rm -rf "./.git"
          echo "Overwriting installed dependency in $ST_LIBS_DIR/lsp_utils"
          rm -rf "$ST_LIBS_DIR/lsp_utils"
          mv "./lsp_utils" "$ST_LIBS_DIR"
          cd -

      - name: Run tests
        uses: SublimeText/UnitTesting/actions/run-tests@v1

  lint:
    runs-on: ubuntu-latest
    needs: tags
    steps:
      - uses: actions/checkout@v6
        with:
          path: lsp_utils

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - run: |
          sudo apt update
          sudo apt install --no-install-recommends -y x11-xserver-utils

      - name: Clone dependencies for type checking
        run: |
          git clone --branch "${{ needs.tags.outputs.lsp_tag }}" --depth 1 https://github.com/sublimelsp/LSP.git
          git clone --branch "${{ needs.tags.outputs.sublime_lib_tag }}" --depth 1 https://github.com/SublimeText/sublime_lib.git

      - run: pip3 install mypy==1.19.1 flake8==7.3.0 pyright==1.1.408 --user
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - run: |
          cd lsp_utils
          mypy lsp_utils
          flake8 lsp_utils tests
          pyright lsp_utils
